[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pangeo2docker"
author = "Tom Augspurger"
author-email = "tom.augspurger88@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

