channels:
  - conda-forge
dependencies:
  # - conda
  - python=3.7
  - jupyterhub=1.1.0
  - jupyterlab==1.2.6
  - jupyter-server-proxy=1.2.0
  - dask==2.10.1
  - dask-labextension=1.1.0
  - dask-kubernetes=0.10.1
  - dask-gateway=0.6.1
  - tornado=6.0.3
  - bokeh=1.4
  - xarray=0.15.0
  - pip=20.0.2
